# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeometricAttributes
                                 A QGIS plugin
 A set of tools for the automated and objective classification of geometry and shape of modern depositional elements
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-08-26
        copyright            : (C) 2019 by Bjorn Nyberg
        email                : bjorn.nyberg@uib.no
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Bjorn Nyberg'
__date__ = '2019-08-26'
__copyright__ = '(C) 2019 by Bjorn Nyberg'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeometricAttributes class from file GeometricAttributes.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geometric_attributes import GeometricAttributesPlugin
    return GeometricAttributesPlugin()
